name: "Sample"
on:
  pull_request:
    types:
      - opened

jobs:
  sample:
    runs-on: ubuntu-latest
    name: Sample
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Sample action
        uses: ./
        with:
          github-token: ${{ secrets.SAMPLE_PAT }}
          target-organization-name: 'Sample-Test-Purpose'
          target-team-name: 'sample'
          pr-repo-owner: 'hoony9x'
          pr-repo-name: 'Assign-Random-Reviewer'
          pr-number: ${{ github.event.pull_request.number }}
          pr-author: ${{ github.event.pull_request.user.login }}